### ISSUE TITLE
images gets broken when being copied

### ISSUE THREAD

**Issue by mchampaneri** [hilmanski/mini-SSG-website#1]

**Comment by hilmanski** [comment]
hi @mchampaneri thanks for letting me know

**Comment by hilmanski** [comment]
Hi @mchampaneri 
I resolved this issue, in [v 0.2 ](https://www.npmjs.com/package/mini-ssg) you can reinstall it now.

Notes:
Now all static files and folder live in '/dev/static'
so if you have any assets like JS, CSS, images, sitemap.xml etc... you can put it here, whether directly or in a subfolder
